services:
  alura-db:
    image: postgres:latest
    container_name: alura-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_login_users_db
    ports:
      - "5432:5432"
    networks:
      - redelocal
  alura-app:
    build:
      context: './tc5-api-products'
      dockerfile: Dockerfile
    image: product-app:latest
    container_name: alura-app
    environment:
      - SPRING_SERVER_PORT=8081
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://product-db:5434/api_carts_db
      - SPRING_DATA_SOURCE_USERNAME=admin
      - SPRING_DATA_SOURCE_PASSWORD=admin
      - SPRING_JWT_SECRET=YmF0bWFuIGJhdG1hbiBiYXRtYW4=
    ports:
      - "8081:8081"
    networks:
      - redelocal
    depends_on:
      - alura-db

networks:
  redelocal:

volumes:
  postgres-data:
